### ISSUE TITLE
Sun no longer visible from version 1.1

### ISSUE THREAD

**Issue by slipher** [UnvanquishedAssets/map-station15_src.dpkdir#16]
The sun does not show up in recent versions of the map, starting from version 1.1. `map-station15_1.0~1.pk3` works in 0.54 (if renamed to dpk). I believe this is the last version with JPEG textures. `map-station15-r1_trem.dpk` also works in 0.54. `map-station15_1.0+2.pk3`, the last release before 1.1, cannot be tested on recent engines due to the Crunch update, but it is known to work in 0.50. The sun shaders are identical modulo path names, so I assume it's something changed in the BSP.

**Comment by illwieckz** [comment]
It looks to be already fixed in `master` branch:

![unvanquished_2024-10-12_175215_000](https://github.com/user-attachments/assets/860ed647-d54c-4bba-b14f-53610b3f5313)
