### ISSUE TITLE
new grass is not displayed correctly

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/map-station15_src.dpkdir#2]
new grass is not displayed correctly:

[![wrong grass](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-28_015608_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-28_015608_000.jpg)

The grass texture is a new texture by Keziolio, perhaps something has to be adjusted in shader or something like that.

It only happens on newly compiled map, the already build map (the one compiled against old textures) is fine.

**Comment by illwieckz** [comment]
what I get:

[![wrong grass](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-28_034709_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-28_034709_000.jpg)

what we expect:

[![correct grass](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-29_230514_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/station15/grass/unvanquished_2018-04-29_230514_000.jpg)

**Comment by JacksonTech** [comment]
Strange. Any errors in texture loading?

The shader does use two layered textures (one dirt, one grass) as controlled by the alpha brushes in the .map, so you'll definitely need to adjust the shader if you changed the texture file names.

Do the textures have alpha channels?

**Comment by illwieckz** [comment]
the texture file names have not changed, that's why it works when we swap the files within the pk3 without recompilation (second picture on previous comment).

**Comment by illwieckz** [comment]
the `ter_mud1` texture has alpha channel, but the `ter_moss1` does not have one. And well, if it has, it would probably be dropped by crunch because being plain white.

**Comment by illwieckz** [comment]
on a similar topic with terrain blending (thunder map), some words from IRC:

> illwieckz:
> I read in [xreal shader manual](http://tremap.xtr3m.net/__Games/Xreal/Manual_Shader_1/ShaderManual.htm#DestinationBlend.3CdstBlend.3E) this thing:
> ```
> GL_SRC_ALPHA
>      The TGA file being used for the Source data must have an alpha channel
>      in addition to its RGB channels (for a total of four channels).
>      The alpha channel is an 8-bit black and white only channel.
>      An entirely white alpha channel will not darken the Source.
> ```
> wouldn't be nice to add this alpha channel and set it to white if missing?
> I have a feeling that terrain blending needs this alpha channel, even if it's completely white
> but when alpha is completely white, it can be lost by some optimization in compression process
> 
> perturbed:
> i don't get it, if you don't have an alpha then why not don't put GL_SRC_ALPHA
> 
> illwieckz:
> https://github.com/UnvanquishedAssets/map-thunder_src.dpkdir/blob/50c7f9f4131614ce23cd148c0f961dbd697fe5e0/scripts/thunder.shader#L397-L423
> 
> ```
> textures/thunder/ter_rocksand_yz
> {
> 	qer_editorimage textures/thunder/ter_rocksand_p
> 	q3map_nonplanar
> 	q3map_shadeAngle 90
> 	q3map_tcGen ivector ( 0 256 0 ) ( 0 0 256 )
> 	q3map_alphaMod dotproduct2 ( 0.0 0.0 0.75 )
> 
> 	{
> 		map textures/thunder/pk02_rock01_d
> 		rgbGen identity
> 	}
> 
> 	{
> 		map textures/thunder/pk02_sand01_d
> 		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
> 		alphaFunc GE128
> 		rgbGen identity
> 		alphaGen vertex
> 	}
> 
> 	{
> 		map $lightmap
> 		blendFunc GL_DST_COLOR GL_ZERO
> 		rgbGen identity
> 	}
> }
> ```
> 
> map textures/thunder/pk02_sand01_d has white alpha channel; which is lost in compression
> this texture is expected to be merged with pk02_rock_d using alpha channel
> then, starts the thing I'm not sure to really understand
> there is a q3map_alphaMod keyword
> and, not visible here, map is full of terrain blending volumes, using shaders like that:
> https://github.com/UnvanquishedAssets/tex-common_src.dpkdir/blob/6037efc20e727a002b6426c1ccf92bd2693fc8ce/scripts/common.shader#L410-L421
> 
> ```
> textures/common/alpha_025
> {
> 	qer_editorimage textures/common_src/alpha_025
> 	qer_trans 0.80
> 
> 	q3map_alphaMod volume
> 	q3map_alphaMod set 0.25
> 
> 	surfaceparm trans
> 	surfaceparm nodraw
> 	surfaceparm nonsolid
> }
> ```
> 
> I have a feeling those are alpha modifier and I fear that they only work on existing alpha channel but will not create it if inexistent before
> it's probably a q3map2 issue, not a dæmon one
> those textures lost alpha channel on crunch process and it works
> but the mapper probably had tga with alpha channels while compiling
> or perhaps I understand nothing about it
> but I don't know why terrain blending does not work

**Comment by illwieckz** [comment]
I don't know what happened but it now works.

**Comment by illwieckz** [comment]
As a side note, I'm not sure the alphagen terrain operation produces what it is asked to, but the result looks good so it's OK.
